name: idp-huaweicloud
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  say-hello:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.10.0 @actions/http-client npm install @huaweicloud/huaweicloud-sdk-core @huaweicloud/huaweicloud-sdk-ecs @huaweicloud/huaweicloud-sdk-iam uuid
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken("set_by_owner")
            coredemo.setOutput('id_token', id_token)
      - name: write idtoken to temp file
        id: write
        run: |
          # 选系统临时目录（$RUNNER_TEMP 每次 job 都会清）
          TMPFILE="$RUNNER_TEMP/mystr.txt"
          # 也可以自己 mkdir 目录
          echo '${{steps.idtoken.outputs.id_token}}' > "$TMPFILE"
          # 把路径 export 给后续 step
          echo "TMPFILE=$TMPFILE" >> "$GITHUB_ENV"
      - name: Login huaweicloud
        id: login
        run: |
          curl -ki -L -X POST -H "Authorization: Bearer ${{steps.idtoken.outputs.id_token}}" https://iam.myhuaweicloud.com/v3/OS-FEDERATION/identity_providers/MyGitHubAction/protocols/oidc/auth -H "Accept: application/json;" -H "Content-Type: application/json" -d "{}"
          unscoped_token=$(curl -ki -s -X POST -H "Authorization: Bearer ${{steps.idtoken.outputs.id_token}}" https://iam.myhuaweicloud.com/v3/OS-FEDERATION/identity_providers/MyGitHubAction/protocols/oidc/auth -H "Accept: application/json;" -H "Content-Type: application/json" -d "{}" | grep 'X-Subject-Token:' | awk '{print $2}')
          echo "unscoped=${unscoped_token}" >> $GITHUB_OUTPUT
          response=$(curl -L -X POST 'https://iam.cn-north-4.myhuaweicloud.com/v3.0/OS-CREDENTIAL/securitytokens' -H "x-auth-token: $unscoped_token" -H 'Content-Type: application/json' -d '{"auth":{"identity":{"methods":["token"]}}}')
          echo "response=${response}" >> $GITHUB_OUTPUT
          access=$(python -c "import json; print(json.loads('$response')['credential']['access'])")
          secret=$(python -c "import json; print(json.loads('$response')['credential']['secret'])")
          securitytoken=$(python -c "import json; print(json.loads('$response')['credential']['securitytoken'])")
          echo "access=${access}" >> $GITHUB_OUTPUT
          echo "secret=${secret}" >> $GITHUB_OUTPUT
          echo "securitytoken=${securitytoken}" >> $GITHUB_OUTPUT
      - name: Set up KooCLI
        run: |
          sudo mkdir -p /usr/local/hcloud
          curl -LO https://hwcloudcli.obs.cn-north-1.myhuaweicloud.com/cli/latest/huaweicloud-cli-linux-amd64.tar.gz
          sudo tar -zxvf huaweicloud-cli-linux-amd64.tar.gz -C /usr/local/hcloud
          sudo chmod a+x /usr/local/hcloud/hcloud
        id: setup
      - name: Show Specific Version Info of ECS by KooCLI
        id: show
        run: |
          /usr/local/hcloud/hcloud configure set --cli-profile=testAKSKST --cli-mode=AKSK --cli-region=cn-north-4 --cli-access-key=${{steps.login.outputs.access}} --cli-secret-key=${{steps.login.outputs.secret}} --cli-security-token=${{steps.login.outputs.securitytoken}} --cli-domain-id=0cf8083a8980f4210f31c01864aecda0 --cli-read-timeout=10 --cli-connect-timeout=5 --cli-agree-privacy-statement=true
          /usr/local/hcloud/hcloud ECS NovaShowVersion --cli-region="cn-north-4" --api_version="v2.1"
          /usr/local/hcloud/hcloud ECS ListCloudServers --cli-region="cn-north-4"
      - name: Show ECS by SDK
        uses: actions/github-script@v6
        id: showsdk
        with:
          script: |
            const coresdk = require('@huaweicloud/huaweicloud-sdk-core');
            const ecs = require("@huaweicloud/huaweicloud-sdk-ecs/v2/public-api");            
            const credentials = new coresdk.BasicCredentials().withAk('${{steps.login.outputs.access}}').withSk('${{steps.login.outputs.secret}}').withProjectId('06a82cfd9e80105d2fd3c0103c70f948').withSecurityToken('${{steps.login.outputs.securitytoken}}')
            const client = ecs.EcsClient.newBuilder().withCredential(credentials).withEndpoint('https://ecs.cn-north-4.myhuaweicloud.com').build()
            const request = new ecs.ListCloudServersRequest()
            const result = client.listCloudServers(request)
            result.then(result => {console.log("JSON.stringify(result)::" + JSON.stringify(result))}).catch(ex => {console.log("exception:" + JSON.stringify(ex));})
            const {stringify} = require('flatted');
            const retjson = stringify(result)
            console.log('retjson：', retjson)
            console.log(typeof result)
            console.log(Object.keys(result).join(','))
            const coredemo = require('@actions/core')
            coredemo.setOutput('retjson', retjson)
            const fs = require('fs')
            const str = fs.readFileSync(process.env.TMPFILE, 'utf8')
            console.log('Node 读到：', str)
      - name: Show ECS by SDK idtoken
        uses: actions/github-script@v6
        id: showsdkidp
        with:
          script: |
            const coresdk = require('@huaweicloud/huaweicloud-sdk-core');
            const ecs = require("@huaweicloud/huaweicloud-sdk-ecs/v2/public-api");            
            const credentials = new coresdk.BasicCredentials().withIdpId('MyGitHubAction').withIdTokenFile(process.env.TMPFILE).withProjectId('06a82cfd9e80105d2fd3c0103c70f948')
            const client = ecs.EcsClient.newBuilder().withCredential(credentials).withEndpoint('https://ecs.cn-north-4.myhuaweicloud.com').build()
            const request = new ecs.ListCloudServersRequest()
            const result = client.listCloudServers(request)
            result.then(result => {console.log("idp result::" + JSON.stringify(result))}).catch(ex => {console.log("exception:" + JSON.stringify(ex));})
            const fs = require('fs')
            const str = fs.readFileSync(process.env.TMPFILE, 'utf8')
            console.log('Node 读到：', str)
      - name: Show IAM Group by SDK idtoken
        uses: actions/github-script@v6
        id: showIAMforidp
        with:
          script: |
            const coresdk = require('@huaweicloud/huaweicloud-sdk-core');   
            const iam = require("@huaweicloud/huaweicloud-sdk-iam/v3/public-api");
            const domain_id = "120658a586a949e4b5b353c4ce4fd82f";
            const credentials = new core.GlobalCredentials().withIdpId('MyGitHubAction').withIdTokenFile(process.env.TMPFILE).withDomainId(domain_id)
            const client = iam.IamClient.newBuilder().withCredential(credentials).withEndpoint(endpoint).build()
            const request = new iam.KeystoneListGroupsRequest()
            request.domainId = "120658a586a949e4b5b353c4ce4fd82f"
            const result = client.keystoneListGroups(request)
            result.then(result => {console.log("idp result::" + JSON.stringify(result))}).catch(ex => {console.log("exception:" + JSON.stringify(ex));})
